volumes:
  db:
  redis:

services:
  php:
    image: vspoint/php:8.4-fpm-dev
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - .:/srv
      - ./.docker/dev/php/conf.d/99-extra.ini:/usr/local/etc/php/conf.d/99-extra.ini
      #- ./.docker/dev/php/php-fpm.d/99-extra.ini:/usr/local/etc/php-fpm.d/99-extra.ini
      #- ./.docker/dev/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      #- ./.k8s/overlays/dev/configmap/php/conf.d/99-extra.ini:/usr/local/etc/php/conf.d/99-extra.ini
    working_dir: /srv
    user: ${UID:-1000}:${GID:-1000}

  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./public:/srv/public
      - ./.docker/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      #- ./.k8s/base/configmap/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:17.4-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:7.4.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
